"use client"

import { useEffect, useState, useRef } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { motion, useInView, AnimatePresence } from "framer-motion"
import {
    GraduationCap, Upload, Brain, Zap, BarChart3,
    ArrowRight, CheckCircle, AlertTriangle, Users,
    School, TrendingDown, Lightbulb, Globe, Moon, Sun,
    ChevronDown, Star, Shield, Clock
} from "lucide-react"
import { useDarkMode } from "@/lib/useDarkMode"

function AnimatedNumber({ value, duration = 2000 }: { value: number; duration?: number }) {
    const [display, setDisplay] = useState(0)
    const ref = useRef<HTMLSpanElement>(null)
    const inView = useInView(ref, { once: true })

    useEffect(() => {
        if (!inView) return
        let start = 0
        const steps = 60
        const inc = value / steps
        const timer = setInterval(() => {
            start += inc
            if (start >= value) { setDisplay(value); clearInterval(timer) }
            else setDisplay(Math.round(start))
        }, duration / steps)
        return () => clearInterval(timer)
    }, [inView, value, duration])

    return <span ref={ref}>{display.toLocaleString()}</span>
}

function Section({ children, className = "" }: { children: React.ReactNode; className?: string }) {
    const ref = useRef(null)
    const inView = useInView(ref, { once: true, margin: "-80px" })
    return (
        <motion.div
            ref={ref}
            initial={{ opacity: 0, y: 40 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, ease: [0.4, 0, 0.2, 1] }}
            className={className}
        >
            {children}
        </motion.div>
    )
}

export default function LandingPage() {
    const router = useRouter()
    const { isDark, toggle, mounted } = useDarkMode()
    const [scrolled, setScrolled] = useState(false)
    const [activeStep, setActiveStep] = useState(0)

    useEffect(() => {
        const handleScroll = () => setScrolled(window.scrollY > 20)
        window.addEventListener("scroll", handleScroll)
        return () => window.removeEventListener("scroll", handleScroll)
    }, [])

    const handleLoginClick = () => {
        const token = localStorage.getItem("token")
        if (token) {
            router.push("/dashboard")
        } else {
            router.push("/auth")
        }
    }

    useEffect(() => {
        const timer = setInterval(() => {
            setActiveStep((prev) => (prev + 1) % 4)
        }, 2500)
        return () => clearInterval(timer)
    }, [])

    const steps = [
        {
            icon: Upload,
            color: "var(--accent-blue)",
            bg: "var(--accent-blue-light)",
            step: "01",
            title: "Upload attendance data",
            desc: "BEOs upload a simple CSV with student attendance records and mid-term marks. The system accepts photos of physical mark sheets via AI-powered OCR.",
            detail: "Drag & drop CSV · EasyOCR mark sheet scanning · 200 students in 30 seconds",
        },
        {
            icon: Brain,
            color: "var(--accent-amber)",
            bg: "var(--accent-amber-light)",
            step: "02",
            title: "AI predicts dropout risk",
            desc: "Our XGBoost model analyses 10+ features — absence streaks, grade dips, seasonal patterns — and generates a risk score for each student with a 60-day prediction window.",
            detail: "XGBoost · AUC-ROC 0.97 · 60-day early warning",
        },
        {
            icon: Lightbulb,
            color: "var(--accent-red)",
            bg: "var(--accent-red-light)",
            step: "03",
            title: "Get intervention suggestions",
            desc: "Every high-risk student gets a personalised action plan generated by a RAG pipeline over Pratham and ASER research evidence. Not just a score — a specific next step.",
            detail: "LangChain RAG · ChromaDB · Pratham ASER evidence base",
        },
        {
            icon: BarChart3,
            color: "var(--accent-green)",
            bg: "var(--accent-green-light)",
            step: "04",
            title: "Track intervention outcomes",
            desc: "Log actions taken, record 30-day follow-up scores, and measure your success rate. See exactly which interventions worked and which schools improved most.",
            detail: "Before/after tracking · Success rate · Impact dashboard",
        },
    ]

    const features = [
        { icon: Brain, title: "XGBoost ML Model", desc: "Trained on structured tabular data — the gold standard for attendance and grade prediction. AUC-ROC of 0.97 on synthetic + real anonymised data.", color: "var(--accent-blue)" },
        { icon: Upload, title: "EasyOCR Integration", desc: "Teachers photograph physical mark sheets. AI reads and digitises grades automatically — no manual data entry needed in rural schools.", color: "var(--accent-amber)" },
        { icon: Lightbulb, title: "RAG-Powered Suggestions", desc: "LangChain + ChromaDB retrieves relevant intervention strategies from Pratham Annual Reports and ASER 2022 evidence base for each student profile.", color: "var(--accent-red)" },
        { icon: Globe, title: "7 Indian Languages", desc: "Full UI in English, Hindi, Tamil, Telugu, Marathi, Bengali, and Kannada. Built for government officers across all Indian states.", color: "var(--accent-green)" },
        { icon: Shield, title: "Privacy-First Design", desc: "All demo data is synthetic. Real deployment uses anonymised student IDs. No personally identifiable information leaves the block server.", color: "var(--accent-blue)" },
        { icon: Clock, title: "60-Day Early Warning", desc: "EduSight flags students months before they actually drop out — giving educators a full window to intervene before the decision is made.", color: "var(--accent-amber)" },
    ]

    const stats = [
        { value: 14000000, label: "students lost annually", sublabel: "Class 6–10, India", color: "var(--accent-red)" },
        { value: 60, label: "day early warning", sublabel: "before dropout occurs", color: "var(--accent-blue)" },
        { value: 97, label: "% model accuracy", sublabel: "AUC-ROC on test data", color: "var(--accent-green)" },
        { value: 7, label: "languages supported", sublabel: "across Indian states", color: "var(--accent-amber)" },
    ]

    return (
        <div style={{ background: "var(--neu-bg)", minHeight: "100vh", overflowX: "hidden" }}>

            {/* ═══════════ NAVBAR ═══════════ */}
            <header
                className="sticky top-0 z-50 px-6 md:px-12 py-4 transition-all duration-300"
                style={{
                    background: "var(--neu-bg)",
                    boxShadow: scrolled ? "0 4px 20px rgba(196,202,212,0.8)" : "none",
                }}
            >
                <div className="max-w-6xl mx-auto flex items-center justify-between">
                    <Link href="/landing" className="flex items-center gap-3" style={{ textDecoration: 'none' }}>
                        <div style={{
                            width: "40px", height: "40px", borderRadius: "0.75rem",
                            background: "var(--neu-bg)", boxShadow: "var(--shadow-raised-sm)",
                            display: "flex", alignItems: "center", justifyContent: "center",
                        }}>
                            <GraduationCap size={22} style={{ color: "var(--accent-blue)" }} />
                        </div>
                        <p style={{ fontSize: "24px", fontWeight: 800, color: "var(--text-primary)", letterSpacing: "-0.03em", lineHeight: 1 }}>
                            EduSight
                        </p>
                    </Link>

                    <div className="flex items-center gap-3">
                        {mounted && (
                            <button
                                onClick={toggle}
                                style={{
                                    width: "34px", height: "34px", borderRadius: "0.625rem",
                                    background: "var(--neu-bg)", boxShadow: "var(--shadow-raised-sm)",
                                    border: "none", cursor: "pointer", display: "flex",
                                    alignItems: "center", justifyContent: "center",
                                }}
                            >
                                {isDark
                                    ? <Sun size={14} style={{ color: "var(--accent-amber)" }} />
                                    : <Moon size={14} style={{ color: "var(--accent-blue)" }} />
                                }
                            </button>
                        )}

                        <button
                            onClick={handleLoginClick}
                            style={{
                                background: "var(--accent-blue)",
                                boxShadow: "4px 4px 10px #3451d1, -2px -2px 8px #5571ff",
                                border: "none", borderRadius: "0.75rem", padding: "8px 20px",
                                fontSize: "13px", fontWeight: 600, color: "white",
                                cursor: "pointer", transition: "all 0.15s ease",
                            }}
                        >
                            Get started →
                        </button>
                    </div>
                </div>
            </header>

            {/* ═══════════ HERO ═══════════ */}
            <section className="px-6 md:px-12 pt-16 pb-20 max-w-6xl mx-auto">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">

                    {/* Left */}
                    <div>
                        <motion.div
                            initial={{ opacity: 0, y: -12 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.5 }}
                        >
                            <span style={{
                                fontSize: "11px", fontWeight: 600, letterSpacing: "0.08em",
                                textTransform: "uppercase", color: "var(--accent-blue)",
                                background: "var(--accent-blue-light)",
                                padding: "4px 12px", borderRadius: "999px",
                                display: "inline-block", marginBottom: "16px",
                            }}>
                                🎓 Built for India's Block Education Officers
                            </span>
                        </motion.div>

                        <motion.h1
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.1 }}
                            style={{
                                fontSize: "clamp(2rem, 5vw, 3.25rem)",
                                fontWeight: 800,
                                color: "var(--text-primary)",
                                letterSpacing: "-0.04em",
                                lineHeight: 1.1,
                                marginBottom: "20px",
                            }}
                        >
                            Predict school dropouts{" "}
                            <span style={{ color: "var(--accent-blue)" }}>60 days</span>{" "}
                            before they happen
                        </motion.h1>

                        <motion.p
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.2 }}
                            style={{
                                fontSize: "16px", color: "var(--text-muted)",
                                lineHeight: 1.7, marginBottom: "32px", maxWidth: "480px",
                            }}
                        >
                            India loses <strong style={{ color: "var(--accent-red)" }}>1.4 crore students</strong> between
                            Class 6 and Class 10 every year. EduSight uses AI to identify at-risk students
                            early — giving educators enough time to intervene.
                        </motion.p>

                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.3 }}
                            className="flex flex-wrap gap-3"
                        >
                            <button
                                onClick={handleLoginClick}
                                style={{
                                    background: "var(--accent-blue)",
                                    boxShadow: "4px 4px 14px #3451d1, -2px -2px 8px #5571ff",
                                    border: "none", borderRadius: "1rem",
                                    padding: "14px 28px", fontSize: "15px",
                                    fontWeight: 700, color: "white", cursor: "pointer",
                                    display: "flex", alignItems: "center", gap: "8px",
                                    transition: "all 0.2s ease",
                                }}
                                onMouseEnter={(e) => (e.currentTarget as HTMLElement).style.transform = "translateY(-2px)"}
                                onMouseLeave={(e) => (e.currentTarget as HTMLElement).style.transform = "translateY(0)"}
                            >
                                Launch dashboard <ArrowRight size={16} />
                            </button>

                            <a
                                href="#how-it-works"
                                style={{
                                    background: "var(--neu-bg)",
                                    boxShadow: "var(--shadow-raised-sm)",
                                    borderRadius: "1rem", padding: "14px 24px",
                                    fontSize: "15px", fontWeight: 600,
                                    color: "var(--text-secondary)", textDecoration: "none",
                                    display: "flex", alignItems: "center", gap: "8px",
                                    transition: "all 0.2s ease",
                                }}
                                onMouseEnter={(e) => (e.currentTarget as HTMLElement).style.transform = "translateY(-2px)"}
                                onMouseLeave={(e) => (e.currentTarget as HTMLElement).style.transform = "translateY(0)"}
                            >
                                How it works <ChevronDown size={15} />
                            </a>
                        </motion.div>

                        {/* Trust badges */}
                        <motion.div
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            transition={{ duration: 0.6, delay: 0.5 }}
                            className="flex flex-wrap gap-3 mt-6"
                        >
                            {["✓ ASER 2022 evidence-based", "✓ 7 Indian languages", "✓ Privacy-first"].map((badge) => (
                                <span key={badge} style={{
                                    fontSize: "11px", fontWeight: 600,
                                    color: "var(--text-muted)",
                                    display: "flex", alignItems: "center", gap: "4px",
                                }}>
                                    {badge}
                                </span>
                            ))}
                        </motion.div>
                    </div>

                    {/* Right — Hero visual */}
                    <motion.div
                        initial={{ opacity: 0, x: 40 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.7, delay: 0.2 }}
                    >
                        <div style={{
                            background: "var(--neu-bg)",
                            boxShadow: "var(--shadow-raised)",
                            borderRadius: "1.5rem",
                            padding: "1.5rem",
                            position: "relative",
                        }}>
                            {/* Mock dashboard card */}
                            <div style={{ marginBottom: "12px" }}>
                                <p style={{ fontSize: "11px", fontWeight: 600, color: "var(--text-muted)", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: "8px" }}>
                                    High risk students — Rampur Block
                                </p>
                                {[
                                    { name: "Ravi Kumar", class: "Class 8", score: 97, school: "Govt. PS Rampur", signal: "14 absences · Failed Math" },
                                    { name: "Priya Devi", class: "Class 7", score: 74, school: "Govt. PS Nandpur", signal: "9 absences · Harvest overlap" },
                                    { name: "Arjun Singh", class: "Class 9", score: 68, school: "Govt. PS Lakhanpur", signal: "Grade drop · Science" },
                                ].map((student, i) => (
                                    <motion.div
                                        key={student.name}
                                        initial={{ opacity: 0, x: 20 }}
                                        animate={{ opacity: 1, x: 0 }}
                                        transition={{ delay: 0.4 + i * 0.15 }}
                                        style={{
                                            background: "var(--neu-bg)",
                                            boxShadow: "var(--shadow-inset-sm)",
                                            borderRadius: "0.875rem",
                                            padding: "0.75rem",
                                            marginBottom: "8px",
                                            display: "flex",
                                            alignItems: "center",
                                            gap: "12px",
                                        }}
                                    >
                                        <div style={{
                                            width: "36px", height: "36px", borderRadius: "50%",
                                            background: student.score >= 70 ? "#FDECEA" : "#FEF4EC",
                                            display: "flex", alignItems: "center", justifyContent: "center",
                                            fontSize: "12px", fontWeight: 700,
                                            color: student.score >= 70 ? "#E63946" : "#F4A261",
                                            flexShrink: 0,
                                        }}>
                                            {student.name.split(" ").map(n => n[0]).join("")}
                                        </div>
                                        <div style={{ flex: 1, minWidth: 0 }}>
                                            <p style={{ fontSize: "13px", fontWeight: 600, color: "var(--text-primary)" }}>
                                                {student.name}
                                            </p>
                                            <p style={{ fontSize: "10px", color: "var(--text-muted)", marginTop: "1px" }}>
                                                {student.class} · {student.school}
                                            </p>
                                            <p style={{ fontSize: "10px", color: "var(--accent-red)", marginTop: "2px" }}>
                                                ⚠ {student.signal}
                                            </p>
                                        </div>
                                        <div style={{
                                            width: "40px", height: "40px", borderRadius: "50%",
                                            boxShadow: "var(--shadow-inset-sm)",
                                            display: "flex", alignItems: "center", justifyContent: "center",
                                            flexDirection: "column", flexShrink: 0,
                                        }}>
                                            <span style={{
                                                fontSize: "14px", fontWeight: 800,
                                                color: student.score >= 70 ? "#E63946" : "#F4A261",
                                                fontFamily: "'JetBrains Mono', monospace",
                                                lineHeight: 1,
                                            }}>
                                                {student.score}
                                            </span>
                                        </div>
                                    </motion.div>
                                ))}
                            </div>

                            {/* AI suggestion preview */}
                            <motion.div
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: 1 }}
                                style={{
                                    background: "linear-gradient(135deg, rgba(67,97,238,0.08), rgba(45,198,83,0.06))",
                                    border: "1px solid rgba(67,97,238,0.15)",
                                    borderRadius: "0.875rem",
                                    padding: "0.875rem",
                                }}
                            >
                                <p style={{ fontSize: "10px", fontWeight: 600, color: "var(--accent-green)", marginBottom: "4px", display: "flex", alignItems: "center", gap: "4px" }}>
                                    <Lightbulb size={10} /> AI Suggested Action — Ravi Kumar
                                </p>
                                <p style={{ fontSize: "11px", color: "var(--text-secondary)", lineHeight: 1.5 }}>
                                    Schedule an immediate home visit. Coordinate with parent on flexible attendance during harvest season. Enroll in Pratham TaRL bridge program.
                                </p>
                                <p style={{ fontSize: "10px", color: "var(--text-muted)", marginTop: "6px" }}>
                                    📄 ASER 2022 · 📄 Pratham TaRL Guidelines
                                </p>
                            </motion.div>
                        </div>
                    </motion.div>
                </div>
            </section>

            {/* ═══════════ STATS BAR ═══════════ */}
            <Section>
                <div style={{ padding: "0 1.5rem", maxWidth: "72rem", margin: "0 auto 5rem" }}>
                    <div
                        style={{
                            background: "var(--neu-bg)",
                            boxShadow: "var(--shadow-raised)",
                            borderRadius: "1.5rem",
                            padding: "2rem",
                            display: "grid",
                            gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
                            gap: "2rem",
                        }}
                    >
                        {stats.map((stat) => (
                            <div key={stat.label} style={{ textAlign: "center" }}>
                                <p style={{
                                    fontSize: "2.5rem", fontWeight: 800,
                                    color: stat.color, lineHeight: 1,
                                    fontFamily: "'JetBrains Mono', monospace",
                                }}>
                                    <AnimatedNumber value={stat.value} />
                                    {stat.value === 97 ? "%" : stat.value === 7 ? "" : stat.value === 60 ? "" : "+"}
                                </p>
                                <p style={{ fontSize: "13px", fontWeight: 600, color: "var(--text-primary)", marginTop: "4px" }}>
                                    {stat.label}
                                </p>
                                <p style={{ fontSize: "11px", color: "var(--text-muted)", marginTop: "2px" }}>
                                    {stat.sublabel}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>
            </Section>

            {/* ═══════════ HOW IT WORKS ═══════════ */}
            <section id="how-it-works" style={{ padding: "0 1.5rem 5rem", maxWidth: "72rem", margin: "0 auto" }}>
                <Section>
                    <div style={{ textAlign: "center", marginBottom: "3rem" }}>
                        <span style={{
                            fontSize: "11px", fontWeight: 600, letterSpacing: "0.08em",
                            textTransform: "uppercase", color: "var(--accent-blue)",
                            background: "var(--accent-blue-light)", padding: "4px 12px",
                            borderRadius: "999px", display: "inline-block", marginBottom: "12px",
                        }}>
                            How it works
                        </span>
                        <h2 style={{
                            fontSize: "clamp(1.75rem, 4vw, 2.5rem)", fontWeight: 800,
                            color: "var(--text-primary)", letterSpacing: "-0.03em", lineHeight: 1.2,
                        }}>
                            From raw data to saved futures
                        </h2>
                        <p style={{ fontSize: "15px", color: "var(--text-muted)", marginTop: "12px", maxWidth: "480px", margin: "12px auto 0" }}>
                            Four steps. Thirty seconds. A student's future potentially saved.
                        </p>
                    </div>
                </Section>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">

                    {/* Step selector */}
                    <div className="space-y-4">
                        {steps.map((step, i) => (
                            <Section key={step.step}>
                                <motion.div
                                    onClick={() => setActiveStep(i)}
                                    style={{
                                        background: "var(--neu-bg)",
                                        boxShadow: activeStep === i ? "var(--shadow-inset)" : "var(--shadow-raised)",
                                        borderRadius: "1.25rem",
                                        padding: "1.25rem",
                                        cursor: "pointer",
                                        transition: "all 0.3s ease",
                                        borderLeft: activeStep === i ? `3px solid ${step.color}` : "3px solid transparent",
                                    }}
                                    whileHover={{ scale: 1.01 }}
                                    whileTap={{ scale: 0.99 }}
                                >
                                    <div className="flex items-start gap-4">
                                        <div style={{
                                            width: "44px", height: "44px", borderRadius: "0.875rem",
                                            background: activeStep === i ? step.bg : "var(--neu-bg)",
                                            boxShadow: activeStep === i ? "var(--shadow-inset-sm)" : "var(--shadow-raised-sm)",
                                            display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0,
                                            transition: "all 0.3s ease",
                                        }}>
                                            <step.icon size={20} style={{ color: step.color }} />
                                        </div>
                                        <div style={{ flex: 1 }}>
                                            <div className="flex items-center gap-2 mb-1">
                                                <span style={{
                                                    fontSize: "10px", fontWeight: 700, color: step.color,
                                                    fontFamily: "'JetBrains Mono', monospace",
                                                    background: step.bg, padding: "2px 8px", borderRadius: "999px",
                                                }}>
                                                    STEP {step.step}
                                                </span>
                                            </div>
                                            <p style={{ fontSize: "14px", fontWeight: 700, color: "var(--text-primary)", marginBottom: "4px" }}>
                                                {step.title}
                                            </p>
                                            <AnimatePresence>
                                                {activeStep === i && (
                                                    <motion.div
                                                        initial={{ height: 0, opacity: 0 }}
                                                        animate={{ height: "auto", opacity: 1 }}
                                                        exit={{ height: 0, opacity: 0 }}
                                                        transition={{ duration: 0.3 }}
                                                        style={{ overflow: "hidden" }}
                                                    >
                                                        <p style={{ fontSize: "13px", color: "var(--text-muted)", lineHeight: 1.6, marginBottom: "8px" }}>
                                                            {step.desc}
                                                        </p>
                                                        <p style={{
                                                            fontSize: "11px", color: step.color, fontWeight: 600,
                                                            background: step.bg, padding: "4px 10px",
                                                            borderRadius: "999px", display: "inline-block",
                                                        }}>
                                                            {step.detail}
                                                        </p>
                                                    </motion.div>
                                                )}
                                            </AnimatePresence>
                                        </div>
                                    </div>
                                </motion.div>
                            </Section>
                        ))}
                    </div>

                    {/* Step visual preview */}
                    <div style={{ position: "sticky", top: "100px" }}>
                        <AnimatePresence mode="wait">
                            <motion.div
                                key={activeStep}
                                initial={{ opacity: 0, y: 20, scale: 0.97 }}
                                animate={{ opacity: 1, y: 0, scale: 1 }}
                                exit={{ opacity: 0, y: -20, scale: 0.97 }}
                                transition={{ duration: 0.35 }}
                                style={{
                                    background: "var(--neu-bg)",
                                    boxShadow: "var(--shadow-raised)",
                                    borderRadius: "1.5rem",
                                    padding: "2rem",
                                    minHeight: "320px",
                                    display: "flex",
                                    flexDirection: "column",
                                    alignItems: "center",
                                    justifyContent: "center",
                                    textAlign: "center",
                                }}
                            >
                                {activeStep === 0 && (
                                    <div className="w-full space-y-3">
                                        <div style={{ boxShadow: "var(--shadow-inset)", borderRadius: "1rem", padding: "2rem", marginBottom: "12px" }}>
                                            <Upload size={40} style={{ color: "var(--accent-blue)", margin: "0 auto 12px" }} />
                                            <p style={{ fontSize: "14px", fontWeight: 600, color: "var(--text-primary)" }}>Drop your CSV here</p>
                                            <p style={{ fontSize: "12px", color: "var(--text-muted)", marginTop: "4px" }}>students.csv · 200 records</p>
                                        </div>
                                        <div style={{ background: "var(--accent-blue-light)", borderRadius: "0.75rem", padding: "0.75rem" }}>
                                            <p style={{ fontSize: "12px", color: "var(--accent-blue)", fontWeight: 600 }}>✓ 200 students uploaded · Processing...</p>
                                        </div>
                                    </div>
                                )}

                                {activeStep === 1 && (
                                    <div className="w-full space-y-3">
                                        <p style={{ fontSize: "11px", color: "var(--text-muted)", marginBottom: "12px", fontWeight: 600, letterSpacing: "0.06em", textTransform: "uppercase" }}>
                                            XGBoost risk scores
                                        </p>
                                        {[
                                            { name: "Ravi Kumar", score: 97, color: "#E63946" },
                                            { name: "Priya Devi", score: 74, color: "#F4A261" },
                                            { name: "Arjun Singh", score: 68, color: "#F4A261" },
                                            { name: "Sunita Verma", score: 23, color: "#2DC653" },
                                        ].map((s) => (
                                            <div key={s.name} style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                                                <span style={{ fontSize: "12px", color: "var(--text-secondary)", width: "90px", textAlign: "left" }}>{s.name}</span>
                                                <div style={{ flex: 1, height: "8px", background: "var(--neu-bg)", boxShadow: "var(--shadow-inset-sm)", borderRadius: "999px", overflow: "hidden" }}>
                                                    <motion.div
                                                        initial={{ width: 0 }}
                                                        animate={{ width: `${s.score}%` }}
                                                        transition={{ duration: 0.8, ease: "easeOut" }}
                                                        style={{ height: "100%", background: s.color, borderRadius: "999px" }}
                                                    />
                                                </div>
                                                <span style={{ fontSize: "13px", fontWeight: 800, color: s.color, fontFamily: "'JetBrains Mono', monospace", width: "30px" }}>
                                                    {s.score}
                                                </span>
                                            </div>
                                        ))}
                                    </div>
                                )}

                                {activeStep === 2 && (
                                    <div className="w-full">
                                        <div style={{ boxShadow: "var(--shadow-inset-sm)", borderRadius: "1rem", padding: "1rem", marginBottom: "12px", textAlign: "left" }}>
                                            <p style={{ fontSize: "11px", fontWeight: 700, color: "#2DC653", marginBottom: "8px", display: "flex", alignItems: "center", gap: "4px" }}>
                                                <Lightbulb size={11} /> AI Suggested Action
                                            </p>
                                            <p style={{ fontSize: "12px", color: "var(--text-secondary)", lineHeight: 1.6 }}>
                                                1. Schedule home visit within 48 hours<br />
                                                2. Create flexible attendance plan<br />
                                                3. Enroll in Pratham TaRL program<br />
                                                4. Follow up in 2 weeks
                                            </p>
                                        </div>
                                        <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                                            {["📄 ASER 2022", "📄 Pratham TaRL", "📄 MoE Data"].map((s) => (
                                                <span key={s} style={{ fontSize: "10px", padding: "3px 8px", borderRadius: "999px", background: "var(--accent-blue-light)", color: "var(--accent-blue)", fontWeight: 600 }}>
                                                    {s}
                                                </span>
                                            ))}
                                        </div>
                                    </div>
                                )}

                                {activeStep === 3 && (
                                    <div className="w-full space-y-3">
                                        <div className="grid grid-cols-2 gap-3">
                                            {[
                                                { label: "Interventions", value: "12", color: "var(--accent-blue)" },
                                                { label: "Success rate", value: "75%", color: "var(--accent-green)" },
                                                { label: "Avg before", value: "82", color: "var(--accent-red)" },
                                                { label: "Avg after", value: "41", color: "var(--accent-green)" },
                                            ].map((m) => (
                                                <div key={m.label} style={{ boxShadow: "var(--shadow-inset-sm)", borderRadius: "0.75rem", padding: "0.875rem", textAlign: "center" }}>
                                                    <p style={{ fontSize: "1.5rem", fontWeight: 800, color: m.color, fontFamily: "'JetBrains Mono', monospace", lineHeight: 1 }}>
                                                        {m.value}
                                                    </p>
                                                    <p style={{ fontSize: "11px", color: "var(--text-muted)", marginTop: "4px" }}>{m.label}</p>
                                                </div>
                                            ))}
                                        </div>
                                        <div style={{ background: "var(--accent-green-light)", borderRadius: "0.75rem", padding: "0.75rem" }}>
                                            <p style={{ fontSize: "12px", color: "var(--accent-green)", fontWeight: 600 }}>
                                                🎉 8 students potentially saved this month
                                            </p>
                                        </div>
                                    </div>
                                )}
                            </motion.div>
                        </AnimatePresence>

                        {/* Step dots */}
                        <div className="flex justify-center gap-2 mt-4">
                            {steps.map((_, i) => (
                                <button
                                    key={i}
                                    onClick={() => setActiveStep(i)}
                                    style={{
                                        width: activeStep === i ? "24px" : "8px",
                                        height: "8px",
                                        borderRadius: "999px",
                                        background: activeStep === i ? "var(--accent-blue)" : "var(--text-muted)",
                                        border: "none", cursor: "pointer",
                                        transition: "all 0.3s ease",
                                        opacity: activeStep === i ? 1 : 0.4,
                                    }}
                                />
                            ))}
                        </div>
                    </div>
                </div>
            </section>

            {/* ═══════════ FEATURES GRID ═══════════ */}
            <section style={{ padding: "0 1.5rem 5rem", maxWidth: "72rem", margin: "0 auto" }}>
                <Section>
                    <div style={{ textAlign: "center", marginBottom: "3rem" }}>
                        <span style={{
                            fontSize: "11px", fontWeight: 600, letterSpacing: "0.08em",
                            textTransform: "uppercase", color: "var(--accent-green)",
                            background: "var(--accent-green-light)", padding: "4px 12px",
                            borderRadius: "999px", display: "inline-block", marginBottom: "12px",
                        }}>
                            Technical capabilities
                        </span>
                        <h2 style={{
                            fontSize: "clamp(1.75rem, 4vw, 2.5rem)", fontWeight: 800,
                            color: "var(--text-primary)", letterSpacing: "-0.03em",
                        }}>
                            Built with production-grade AI
                        </h2>
                    </div>
                </Section>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                    {features.map((f, i) => (
                        <Section key={f.title}>
                            <motion.div
                                whileHover={{ y: -4 }}
                                style={{
                                    background: "var(--neu-bg)",
                                    boxShadow: "var(--shadow-raised)",
                                    borderRadius: "1.25rem",
                                    padding: "1.5rem",
                                    height: "100%",
                                }}
                            >
                                <div style={{
                                    width: "44px", height: "44px", borderRadius: "0.875rem",
                                    background: "var(--neu-bg)", boxShadow: "var(--shadow-inset-sm)",
                                    display: "flex", alignItems: "center", justifyContent: "center",
                                    marginBottom: "16px",
                                }}>
                                    <f.icon size={20} style={{ color: f.color }} />
                                </div>
                                <p style={{ fontSize: "15px", fontWeight: 700, color: "var(--text-primary)", marginBottom: "8px" }}>
                                    {f.title}
                                </p>
                                <p style={{ fontSize: "13px", color: "var(--text-muted)", lineHeight: 1.6 }}>
                                    {f.desc}
                                </p>
                            </motion.div>
                        </Section>
                    ))}
                </div>
            </section>

            {/* ═══════════ IMPACT SECTION ═══════════ */}
            <section style={{ padding: "0 1.5rem 5rem", maxWidth: "72rem", margin: "0 auto" }}>
                <Section>
                    <div style={{
                        background: "linear-gradient(135deg, rgba(67,97,238,0.1) 0%, rgba(45,198,83,0.08) 100%)",
                        border: "1px solid rgba(67,97,238,0.15)",
                        borderRadius: "1.5rem",
                        padding: "3rem",
                        textAlign: "center",
                        position: "relative",
                        overflow: "hidden",
                    }}>
                        <div style={{
                            position: "absolute", top: "-40px", right: "-40px",
                            width: "160px", height: "160px", borderRadius: "50%",
                            background: "var(--accent-blue)", opacity: 0.05,
                        }} />
                        <div style={{
                            position: "absolute", bottom: "-30px", left: "10%",
                            width: "100px", height: "100px", borderRadius: "50%",
                            background: "var(--accent-green)", opacity: 0.07,
                        }} />

                        <span style={{ fontSize: "40px", display: "block", marginBottom: "16px" }}>🎓</span>
                        <h2 style={{
                            fontSize: "clamp(1.5rem, 4vw, 2.25rem)", fontWeight: 800,
                            color: "var(--text-primary)", letterSpacing: "-0.03em",
                            marginBottom: "16px",
                        }}>
                            Every intervention is a future saved
                        </h2>
                        <p style={{
                            fontSize: "16px", color: "var(--text-muted)", lineHeight: 1.7,
                            maxWidth: "560px", margin: "0 auto 32px",
                        }}>
                            EduSight gives Block Education Officers a <strong style={{ color: "var(--accent-blue)" }}>60-day head start</strong>.
                            That's enough time to visit a home, enrol a student in remedial education,
                            and change the trajectory of a child's life.
                        </p>

                        <div className="flex flex-wrap justify-center gap-4">
                            <button
                                onClick={handleLoginClick}
                                style={{
                                    background: "var(--accent-blue)",
                                    boxShadow: "4px 4px 14px #3451d1",
                                    border: "none", borderRadius: "1rem",
                                    padding: "14px 32px", fontSize: "15px",
                                    fontWeight: 700, color: "white", cursor: "pointer",
                                    display: "flex", alignItems: "center", gap: "8px",
                                    transition: "all 0.2s ease",
                                }}
                                onMouseEnter={(e) => (e.currentTarget as HTMLElement).style.transform = "translateY(-2px)"}
                                onMouseLeave={(e) => (e.currentTarget as HTMLElement).style.transform = "translateY(0)"}
                            >
                                Launch EduSight <ArrowRight size={16} />
                            </button>
                        </div>

                        {/* Feature checklist */}
                        <div className="flex flex-wrap justify-center gap-x-8 gap-y-2 mt-8">
                            {[
                                "Free to use", "No setup required",
                                "Synthetic demo data included", "Works on mobile",
                            ].map((item) => (
                                <span key={item} style={{
                                    fontSize: "12px", color: "var(--text-muted)",
                                    display: "flex", alignItems: "center", gap: "6px",
                                }}>
                                    <CheckCircle size={12} style={{ color: "var(--accent-green)" }} />
                                    {item}
                                </span>
                            ))}
                        </div>
                    </div>
                </Section>
            </section>


        </div>
    )
}